baseURL = "https://msmcs-robotics.github.io/blog"
languageCode = "en-us"
title = "The Robot Club Blog"
theme = "anubis"
paginate = 5
publishDir = "docs"

disqusShortname = ""
googleAnalytics = ""

[author]
name = "MSC/MSMCS Robotics"

[params]
author = "MSC/MSMCS Robotics"
description = "The Blog Site for the MSC/MSMCS Robotics club"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false

# Graphcomment support
graphcommentId = "msmcs_robotics_blog"

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "mainsite"
url = "https://msmcs-robotics.github.io/"

[[params.social]]
id = "github"
url = "https://github.com/msmcs-robotics"

[[params.social]]
id = "instagram"
url = "https://www.instagram.com/msmcsrobotics/"

[[params.social]]
id = "tiktok"
url = "https://www.tiktok.com/@mscrobotics"

[[params.social]]
id = "youtube"
url = "https://www.youtube.com/channel/UCZWf6z_G_wB2OskOX8e_QOw"

[[params.social]]
id = "twitter"
url = "https://twitter.com/msmcsrobotics"

[[params.social]]
id = "twitch"
url = "https://www.twitch.tv/mscrobotics"

[[params.social]]
id = "facebook"
url = "https://www.facebook.com/profile.php?id=100083794482864"

[[params.social]]
id = "email"
url = "mailto:mscroboticsdev@gmail.com"

[[params.social]]
id = "src"
url = "https://github.com/msmcs-robotics/blog"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
