baseURL = "https://msmcs-robotics.github.io/blog"
languageCode = "en-us"
title = "Robo Club Blog"
theme = "anubis"
paginate = 5
publishDir = "docs"

disqusShortname = ""
googleAnalytics = ""

[author]
name = "MSC Robotics"

[params]
author = "MSC Robotics"
description = "The Blog Site for the MSC/MSMCS Robotics club"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "docs"
url = "https://github.com/msmcs-robotics/msmcs-robotics-blog"

[[params.social]]
id = "github"
url = "https://github.com/msmcs-robotics"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
